Switch to debhelper 7 Switch to dh_install instead of dh_movefiles Remove extraneous cruft from debian/rules Use dh_lintian instead of doing it by hand Update init scripts to refer to new names Update maintainer scripts for init script name changes

diff --git a/debian/isc-dhcp-server.postinst b/debian/isc-dhcp-server.postinst
--- a/debian/isc-dhcp-server.postinst
+++ b/debian/isc-dhcp-server.postinst
@@ -70,7 +70,7 @@ if [ ! -e /var/lib/dhcp3/dhcpd.leases ]; then
     fi
 fi
 
-[ -x /sbin/restorecon ] && /sbin/restorecon /var/lib/dhcp3/dhcpd.leases
+[ -x /sbin/restorecon ] && restorecon /var/lib/dhcp3/dhcpd.leases
 
 # If we're upgrading from something before 3.0.2-1 we need to move
 # the symlinks in /etc/rc?.d because we want to fix #292357 for existing
@@ -83,7 +83,7 @@ if dpkg --compare-versions "$2" lt-nl "3.0.2-1"; then
 	done
 fi
 
-update-rc.d dhcp3-server start 40 2 3 4 5 . stop 40 1 . >/dev/null
+update-rc.d isc-dhcp-server start 40 2 3 4 5 . stop 40 1 . >/dev/null
 
 # If we're upgrading from something before 3.1.1-2, we need to remove the
 # shutdown links from /etc/rc{0,6}.d as part of #486518
@@ -91,8 +91,8 @@ if dpkg --compare-versions "$2" lt-nl "3.1.1-2"; then
 	rm -f /etc/rc0.d/K40dhcp3-server /etc/rc6.d/K40dhcp3-server
 fi
 
-# Init script could fail, since dhcp3 is unconfigured on a new install
-invoke-rc.d dhcp3-server start || true
+# Init script could fail, since dhcp is unconfigured on a new install
+invoke-rc.d isc-dhcp-server start || true
 
 db_stop
 
